#include "sd_jwt_zk/api.h"
#include <algorithm>
namespace sd_jwt_zk { namespace {
constexpr std::uint8_t version = 1;
bool utf8(std::string_view s) { int n=0; for (unsigned char c:s) { if(!n) { if(c<0x80) continue; if(c>=0xc2&&c<=0xdf)n=1; else if(c>=0xe0&&c<=0xef)n=2; else if(c>=0xf0&&c<=0xf4)n=3; else return false; } else { if((c&0xc0)!=0x80)return false; --n; } } return n==0; }
void u16(Bytes& o,std::uint16_t n){o.push_back(n>>8);o.push_back(n);}; void u32(Bytes& o,std::uint32_t n){for(int i=3;i>=0;--i)o.push_back(n>>(i*8));}; void u64(Bytes& o,std::uint64_t n){for(int i=7;i>=0;--i)o.push_back(n>>(i*8));}
struct Reader { const Bytes& b; size_t p=0; Result<std::uint8_t> byte(){if(p==b.size())return Result<std::uint8_t>::fail(ErrorCode::malformed,"truncated");return Result<std::uint8_t>::ok(b[p++]);} Result<std::uint16_t> r16(){auto a=byte(),c=byte();if(!a)return Result<std::uint16_t>::fail(a.error->code,a.error->message);if(!c)return Result<std::uint16_t>::fail(c.error->code,c.error->message);return Result<std::uint16_t>::ok((a.value.value()<<8)|c.value.value());} Result<std::uint32_t> r32(){std::uint32_t n=0;for(int i=0;i<4;i++){auto x=byte();if(!x)return Result<std::uint32_t>::fail(x.error->code,x.error->message);n=(n<<8)|x.value.value();}return Result<std::uint32_t>::ok(n);} Result<std::uint64_t> r64(){std::uint64_t n=0;for(int i=0;i<8;i++){auto x=byte();if(!x)return Result<std::uint64_t>::fail(x.error->code,x.error->message);n=(n<<8)|x.value.value();}return Result<std::uint64_t>::ok(n);} Result<Bytes> lp(size_t max){auto n=r32();if(!n)return Result<Bytes>::fail(n.error->code,n.error->message);if(n.value.value()>max||n.value.value()>b.size()-p)return Result<Bytes>::fail(ErrorCode::limit,"invalid bounded length");Bytes x(b.begin()+static_cast<long>(p),b.begin()+static_cast<long>(p+n.value.value()));p+=x.size();return Result<Bytes>::ok(std::move(x));} };
void lp(Bytes&o,const Bytes&x){u32(o,static_cast<std::uint32_t>(x.size()));o.insert(o.end(),x.begin(),x.end());} void lp(Bytes&o,std::string_view x){u32(o,static_cast<std::uint32_t>(x.size()));o.insert(o.end(),x.begin(),x.end());}
Result<void*> limits(const Limits&l,size_t n){return n<=l.max_input?Result<void*>::ok(nullptr):Result<void*>::fail(ErrorCode::limit,"input exceeds bound");}
}
Result<Bytes> encode_identity(const CircuitIdentity& x,const Limits& l){Bytes o{version,static_cast<std::uint8_t>(x.binding),static_cast<std::uint8_t>(x.trust)};if(x.capacity==0||x.field.empty()||!utf8(x.field)||x.field.size()>l.max_field||x.ligero_rate==0||x.query_count==0)return Result<Bytes>::fail(ErrorCode::unsupported,"unsupported circuit parameters");u32(o,x.capacity);o.insert(o.end(),x.circuit_digest.begin(),x.circuit_digest.end());lp(o,x.field);u16(o,x.ligero_rate);u16(o,x.query_count);return limits(l,o.size())?Result<Bytes>::ok(std::move(o)):Result<Bytes>::fail(ErrorCode::limit,"identity exceeds bound");}
Result<CircuitIdentity> decode_identity(const Bytes& b,const Limits&l){if(!limits(l,b.size()))return Result<CircuitIdentity>::fail(ErrorCode::limit,"identity exceeds bound");Reader r{b};auto v=r.byte(),m=r.byte(),t=r.byte();if(!v||!m||!t)return Result<CircuitIdentity>::fail(ErrorCode::malformed,"truncated identity");if(v.value.value()!=version)return Result<CircuitIdentity>::fail(ErrorCode::unsupported,"unknown relation version");if(m.value.value()>2||m.value.value()==0||t.value.value()>2||t.value.value()==0)return Result<CircuitIdentity>::fail(ErrorCode::unsupported,"unknown circuit mode");auto cap=r.r32();if(!cap)return Result<CircuitIdentity>::fail(cap.error->code,cap.error->message);CircuitIdentity x{static_cast<Binding>(m.value.value()),static_cast<Trust>(t.value.value()),cap.value.value(),{},"",0,0};if(x.capacity==0||r.p+32>b.size())return Result<CircuitIdentity>::fail(ErrorCode::malformed,"invalid identity");std::copy_n(b.begin()+static_cast<long>(r.p),32,x.circuit_digest.begin());r.p+=32;auto f=r.lp(l.max_field);auto rate=r.r16();auto q=r.r16();if(!f||!rate||!q)return Result<CircuitIdentity>::fail(ErrorCode::malformed,"truncated identity");x.field.assign(f.value->begin(),f.value->end());x.ligero_rate=rate.value.value();x.query_count=q.value.value();if(!utf8(x.field)||x.field.empty()||!x.ligero_rate||!x.query_count||r.p!=b.size())return Result<CircuitIdentity>::fail(r.p==b.size()?ErrorCode::unsupported:ErrorCode::noncanonical,"noncanonical identity");return Result<CircuitIdentity>::ok(std::move(x));}
Result<Bytes> encode_request(const Request& x,const Limits&l){auto i=encode_identity(x.identity,l);if(!i)return Result<Bytes>::fail(i.error->code,i.error->message);if(!utf8(x.audience)||!utf8(x.nonce)||x.time_min>x.time_max)return Result<Bytes>::fail(ErrorCode::utf8,"invalid request text or time");Bytes o{version};lp(o,*i.value);lp(o,x.audience);lp(o,x.nonce);u64(o,x.time_min);u64(o,x.time_max);lp(o,x.policy);lp(o,x.policy_result);lp(o,x.trust_public);lp(o,x.status_public);return limits(l,o.size())?Result<Bytes>::ok(std::move(o)):Result<Bytes>::fail(ErrorCode::limit,"request exceeds bound");}
Result<Request> decode_request(const Bytes&b,const Limits&l){if(!limits(l,b.size()))return Result<Request>::fail(ErrorCode::limit,"request exceeds bound");Reader r{b};auto v=r.byte();if(!v||v.value.value()!=version)return Result<Request>::fail(ErrorCode::unsupported,"unknown request version");auto ib=r.lp(l.max_field),a=r.lp(l.max_field),n=r.lp(l.max_field);auto lo=r.r64(),hi=r.r64();auto p=r.lp(l.max_field),pr=r.lp(l.max_field),tr=r.lp(l.max_field),st=r.lp(l.max_field);if(!ib||!a||!n||!lo||!hi||!p||!pr||!tr||!st||r.p!=b.size())return Result<Request>::fail(ErrorCode::malformed,"noncanonical request");auto id=decode_identity(*ib.value,l);if(!id)return Result<Request>::fail(id.error->code,id.error->message);Request x{*id.value,std::string(a.value->begin(),a.value->end()),std::string(n.value->begin(),n.value->end()),*lo.value,*hi.value,*p.value,*pr.value,*tr.value,*st.value};if(!utf8(x.audience)||!utf8(x.nonce)||x.time_min>x.time_max)return Result<Request>::fail(ErrorCode::utf8,"invalid request text");return Result<Request>::ok(std::move(x));}
Result<Bytes> encode_envelope(const Envelope&x,const Limits&l){auto r=encode_request(x.request,l);if(!r)return Result<Bytes>::fail(r.error->code,r.error->message);if(x.proof.empty()||x.proof.size()>l.max_proof)return Result<Bytes>::fail(ErrorCode::limit,"invalid proof size");Bytes o{version};lp(o,*r.value);lp(o,x.proof);return limits(l,o.size())?Result<Bytes>::ok(std::move(o)):Result<Bytes>::fail(ErrorCode::limit,"envelope exceeds bound");}
Result<Envelope> decode_envelope(const Bytes&b,const Limits&l){if(!limits(l,b.size()))return Result<Envelope>::fail(ErrorCode::limit,"envelope exceeds bound");Reader r{b};auto v=r.byte();if(!v||v.value.value()!=version)return Result<Envelope>::fail(ErrorCode::unsupported,"unknown envelope version");auto q=r.lp(l.max_input);if(!q)return Result<Envelope>::fail(q.error->code,q.error->message);auto request=decode_request(*q.value,l);if(!request)return Result<Envelope>::fail(request.error->code,request.error->message);if(r.p+4>b.size())return Result<Envelope>::fail(ErrorCode::malformed,"truncated proof length");auto proof=r.lp(l.max_proof);if(!proof||proof.value->empty()||r.p!=b.size())return Result<Envelope>::fail(ErrorCode::noncanonical,"trailing data or invalid proof");return Result<Envelope>::ok({*request.value,*proof.value});}
std::array<std::uint8_t,32> transcript_seed(const Request&x){auto s=encode_request(x);if(!s)return {};std::string in="SDJWT-ZK-V1/transcript";in.append(reinterpret_cast<const char*>(s.value->data()),s.value->size());return sha256_ascii(in);}
} // namespace sd_jwt_zk
